# fly.toml app configuration file generated for chess-js on 2023-10-26T17:16:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chess-js"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  APP_URL = "https://chess-js.fly.dev"
